### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by Suriman** [NRules/NRules#115] opened 2017-05-19 06:10 UTC
Does .NET Core support NRules?

**Comment by jameshulse** [comment] 2017-05-19 09:58
It does as of release `0.6.2` which was released today :) https://github.com/NRules/NRules/releases/tag/v0.6.2

**Comment by snikolayev** [comment] 2017-05-19 12:08
Duplicate of #109

**Closed as completed by snikolayev** 2017-05-19 12:08 UTC
Labels: duplicate
